const PRODUCTS=[
{id:1,name:'Ayvalık Zeytin Fidanı',latin:'Olea europaea',cat:'Meyve',price:349,sun:'Tam güneş',care:'Kolay',tag:'Akdeniz',desc:'Heykelsi gövde, mat gümüş yaprak ve yıllar içinde karakter kazanan zamansız bir bahçe ağacı.',img:'https://images.unsplash.com/photo-1492496913980-501348b61469?auto=format&fit=crop&w=1400&q=88'},
{id:2,name:'Mayer Limon',latin:'Citrus × meyeri',cat:'Meyve',price:429,sun:'Tam güneş',care:'Orta',tag:'Narenciye',desc:'Parlak yaprak, yoğun koku ve canlı sarı meyve; teras ve bahçelerde güçlü Akdeniz vurgusu.',img:'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=1400&q=88'},
{id:3,name:'Lavanta Kümesi',latin:'Lavandula angustifolia',cat:'Çiçek',price:159,sun:'Tam güneş',care:'Kolay',tag:'Aromatik',desc:'Renk kadar kokuyla da çalışan, yürüyüş akslarına ve sınır hatlarına ritim veren aromatik doku.',img:'https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=1400&q=88'},
{id:4,name:'Leylandi',latin:'Cupressocyparis leylandii',cat:'Peyzaj',price:329,sun:'Güneş / yarı gölge',care:'Kolay',tag:'Mahremiyet',desc:'Hızlı gelişen dikey formuyla sınır, perdeleme ve güçlü yeşil arka planlar için etkili seçim.',img:'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=1400&q=88'},
{id:5,name:'Bodur Elma',latin:'Malus domestica',cat:'Meyve',price:389,sun:'Tam güneş',care:'Orta',tag:'Kompakt',desc:'Küçük bahçelerde ve geniş balkonlarda meyve ağacı duygusunu kompakt ölçekte yaşatır.',img:'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?auto=format&fit=crop&w=1400&q=88'},
{id:6,name:'Ortanca',latin:'Hydrangea macrophylla',cat:'Çiçek',price:219,sun:'Yarı gölge',care:'Orta',tag:'Hacim',desc:'Dolgun çiçek başları ve yumuşak tonlarıyla gölgeli köşelere sakin ama güçlü bir hacim kazandırır.',img:'https://images.unsplash.com/photo-1468327768560-75b778cbb551?auto=format&fit=crop&w=1400&q=88'},
{id:7,name:'Ateş Dikeni',latin:'Pyracantha coccinea',cat:'Peyzaj',price:239,sun:'Güneş / yarı gölge',care:'Kolay',tag:'Dört mevsim',desc:'Yaprak, çiçek ve meyveyi yıl boyunca farklı dönemlerde gösteren çok katmanlı peyzaj bitkisi.',img:'https://images.unsplash.com/photo-1512428813834-c702c7702b78?auto=format&fit=crop&w=1400&q=88'},
{id:8,name:'Monstera Deliciosa',latin:'Monstera deliciosa',cat:'Dekoratif',price:289,sun:'Yarı gölge',care:'Kolay',tag:'Tropik',desc:'Geniş ve grafik yapraklarıyla korunaklı teraslara ve iç mekân geçişlerine çağdaş bir vurgu.',img:'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=1400&q=88'}
];
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),money=n=>'₺'+n.toLocaleString('tr-TR');
let active='Tümü',cart=JSON.parse(localStorage.getItem('kilinc-v4-cart')||'[]');
function renderFilters(){const cats=['Tümü','Meyve','Çiçek','Peyzaj','Dekoratif'];$('#filters').innerHTML=cats.map(c=>`<button class="filter ${c===active?'on':''}" data-c="${c}">${c}</button>`).join('');$$('.filter').forEach(b=>b.onclick=()=>{active=b.dataset.c;renderFilters();renderProducts()})}
function renderProducts(){const list=PRODUCTS.filter(p=>active==='Tümü'||p.cat===active);$('#products').innerHTML=list.map(p=>`<article class="product"><div class="productImg"><img loading="lazy" src="${p.img}" alt="${p.name}"><span class="badge">${p.tag}</span></div><div class="productBody"><div class="productTop"><div><h3>${p.name}</h3><div class="latin">${p.latin}</div></div><div class="price">${money(p.price)}</div></div><div class="meta"><span>${p.cat}</span><span>${p.sun}</span><span>${p.care} bakım</span></div><p class="desc">${p.desc}</p><div class="buy"><button onclick="add(${p.id})">Sepete ekle</button><button onclick="document.querySelector('#finder').scrollIntoView({behavior:'smooth'})">Bana uygun mu?</button></div></div></article>`).join('')}
function add(id){const p=PRODUCTS.find(x=>x.id===id),i=cart.find(x=>x.id===id);i?i.qty++:cart.push({...p,qty:1});save();notify(`${p.name} sepete eklendi`)}window.add=add;
function qty(id,d){const i=cart.find(x=>x.id===id);if(!i)return;i.qty+=d;if(i.qty<1)cart=cart.filter(x=>x.id!==id);save()}window.qty=qty;
function save(){localStorage.setItem('kilinc-v4-cart',JSON.stringify(cart));$('#count').textContent=cart.reduce((s,x)=>s+x.qty,0);renderCart()}
function renderCart(){$('#cartList').innerHTML=cart.length?cart.map(x=>`<div class="cartItem"><div><b>${x.name}</b><br><small>${money(x.price)} · ${x.cat}</small></div><div class="qty"><button onclick="qty(${x.id},-1)">−</button><span>${x.qty}</span><button onclick="qty(${x.id},1)">+</button></div></div>`).join(''):`<div class="cartItem"><div><b>Henüz seçim yok.</b><br><small>Butik mağazadan bir bitki ekleyebilirsin.</small></div></div>`;$('#total').textContent=money(cart.reduce((s,x)=>s+x.price*x.qty,0))}
function notify(t){const el=$('#toast');el.textContent=t;el.classList.add('on');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('on'),2100)}
const cartDialog=$('#cartDialog');$('#cartBtn').onclick=()=>cartDialog.showModal();$('#cartClose').onclick=()=>cartDialog.close();$('#checkout').onclick=()=>notify('Ödeme ve WhatsApp sipariş akışı bağlanmaya hazır.');cartDialog.addEventListener('click',e=>{const r=cartDialog.getBoundingClientRect();if(!(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom))cartDialog.close()});
const answers={};$$('.choices').forEach(g=>g.onclick=e=>{if(!e.target.matches('.choice'))return;g.querySelectorAll('.choice').forEach(x=>x.classList.remove('on'));e.target.classList.add('on');answers[g.dataset.q]=e.target.dataset.v;if(Object.keys(answers).length===3){let p;if(answers.space==='balcony')p=answers.care==='easy'?PRODUCTS[2]:PRODUCTS[5];else if(answers.space==='large')p=answers.care==='easy'?PRODUCTS[3]:PRODUCTS[6];else p=answers.sun==='full'?PRODUCTS[0]:PRODUCTS[7];$('#result').innerHTML=`<b>${p.name}</b> seçimlerine en yakın karakter. ${p.sun} sever; bakım seviyesi ${p.care.toLowerCase()}. <button onclick="add(${p.id})">Sepete ekle ↗</button>`}});
$$('.collectionRow').forEach(r=>r.querySelector('.arrowLink').addEventListener('click',()=>{active=r.dataset.filter;renderFilters();renderProducts()}));
const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('in')),{threshold:.08});$$('.reveal').forEach(x=>io.observe(x));
addEventListener('scroll',()=>{const y=scrollY;$('#nav').classList.toggle('scrolled',y>40);const hero=$('.heroMedia');if(hero&&y<innerHeight*1.15)hero.style.transform=`scale(1.03) translateY(${y*.055}px)`},{passive:true});
renderFilters();renderProducts();save();